### ISSUE TITLE
Error: Failed to initialize build "amazon-ebs"

### ISSUE THREAD

**Issue by orsenthil** [aws-samples/amazon-eks-ami-rhel#1]
I am running into this issue with amazon-ebs building with this repo.

```
[cloudshell-user@ip-10-132-61-14 amazon-eks-ami-rhel]$ make 1.28
which: no shfmt in (/home/cloudshell-user/.local/bin:/home/cloudshell-user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/lib/node_modules/aws-cdk/bin)
which: no shellcheck in (/home/cloudshell-user/.local/bin:/home/cloudshell-user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/lib/node_modules/aws-cdk/bin)
make k8s kubernetes_version=1.28.1 kubernetes_build_date=2023-09-14
make[1]: Entering directory '/home/cloudshell-user/amazon-eks-ami-rhel'
which: no shfmt in (/home/cloudshell-user/.local/bin:/home/cloudshell-user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/lib/node_modules/aws-cdk/bin)
which: no shellcheck in (/home/cloudshell-user/.local/bin:/home/cloudshell-user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/lib/node_modules/aws-cdk/bin)
/usr/bin/packer validate -var-file /home/cloudshell-user/amazon-eks-ami-rhel/eks-worker-rhel-variables.json  -var docker_version='none' -var ami_name='amazon-eks-node-rhel-1.28-v202312141901' -var instance_type='t3.large' -var kubernetes_build_date='2023-09-14' -var arch='x86_64' -var ami_component_description='(k8s: {{ user `kubernetes_version` }}, containerd: {{ user `containerd_version` }})' -var kubernetes_version='1.28.1' /home/cloudshell-user/amazon-eks-ami-rhel/eks-worker-rhel.json
Error: Failed to initialize build "amazon-ebs"

The builder amazon-ebs is unknown by Packer, and is likely part of a plugin that
is not installed.
You may find the needed plugin along with installation instructions documented
on the Packer integrations page.

https://developer.hashicorp.com/packer/integrations?filter=amazon


make[1]: *** [Makefile:98: validate] Error 1
make[1]: Leaving directory '/home/cloudshell-user/amazon-eks-ami-rhel'
make: *** [Makefile:128: 1.28] Error 2
```

Suggestions on how to resolve this?

**Comment by bradwatsonaws** [comment]
Hey @orsenthil did you ever get past this issue? It looks to be environmental but hard to confirm based solely on the information above. I see you are attempting this in CloudShell. Is there any more information you can provide such as your region? Did you modify the Makefile at all, or did you leave everything cloned from the repo untouched?

**Comment by andydix** [comment]
I think this might be due to the recent changes to Packer such that you now need to specify a required_plugins section and run packer init...? https://developer.hashicorp.com/packer/docs/commands/init

Although that page states this should only be required for HCL based templates and not JSON.

**Comment by bradwatsonaws** [comment]
> I think this might be due to the recent changes to Packer such that you now need to specify a required_plugins section and run packer init...? https://developer.hashicorp.com/packer/docs/commands/init
> 
> Although that page states this should only be required for HCL based templates and not JSON.

I think you are right, Andy. I started seeing this myself but only in certain scenarios. So I ended up updating the documentation to install this plug-in during the packer installation step. I haven't found that it causes any issues by installing it manually if it isn't needed.

**Comment by hectoralicea** [comment]
adding the below to my  overrideBootstrapCommand and rerunning eksctl to create the cluster worked.  Am continuing testing but so far so good
```
/etc/eks/bootstrap.sh $EKS_CLUSTER
systemctl disable nm-cloud-setup.timer
systemctl disable nm-cloud-setup.service
reboot
```
I had to make other changes for my STIG hardening to work to apply a EKS profile on a already hardened RHEL8 Stig image, but I'll start a new thread with that.

**Comment by orsenthil** [comment]
```
packer plugins install github.com/hashicorp/amazon
```

Helped resolve this issue.
